Fetature 1 mergeto develop branch
Shevadesuyash/Spring-Boot-practice pull request #8
Opened 2024-07-25 05:06 UTC by Shevadesuyash

delete all branch and create again for this merge

2024-07-28 12:03 UTC, spreezy-tech commented
@Shevadesuyash - Rename the title of the PR with appropriate title of the task

2024-07-28 12:06 UTC, spreezy-tech requested changes
@Shevadesuyash  -I see lot of commented code. overall your work looks very clean.  please remoce the commented code if not used

Great job Suyash.

2024-07-28 12:06 UTC, spreezy-tech commented on src/main/java/com/training/test/controller/AuthenticationController.java
> +    //    @Autowired
Remove commented code. it is bad practice to keep unused commented code.

2024-07-29 13:24 UTC, Shevadesuyash commented on src/main/java/com/training/test/controller/AuthenticationController.java
> +
removed comments

2024-07-29 15:12 UTC, Shevadesuyash commented
@spreezy-tech   Code is updated. Removed all unnecessary comments. 
Renamed PR .

2024-08-17 08:03 UTC, Shevadesuyash commented
working code. Deploy on frontend team by creating image of project and run on frontend team.
@spreezy-tech  please check and validate PR  request.

2024-08-18 16:48 UTC, spreezy-tech approved these changes
Great work Suyash. Keep learning. Many more things to explore!

Approved

2024-08-19 05:32 UTC, merged